#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias sudo="sudo -E"
alias m14="cd ~/Sites/Alex/M14"
alias m14-www="cd ~/Sites/Alex/M14/WWW && tmux attach \; new-window \"chromium localhost/M14/WWW && gulp\""
