#!/bin/zsh

install() {
	case $1 in
		all)
			stow --no-folding \
				alacritty \
				base16 \
				bat \
				bin \
				git \
				mime \
				neofetch \
				npm \
				nvim \
				spectrwm \
				spotify \
				startpage \
				vscode \
				xorg \
				zsh
			;;
		*)
			stow --no-folding "$@"
			;;
	esac
}

install "$@"

