#!/bin/zsh

install() {
	case $1 in
		all)
			stow --no-folding \
				alacritty \
				bat \
				dunst \
				git \
				mime \
				neofetch \
				neovim \
				npm \
				openbox \
				pam \
				parcellite \
				picom \
				rofi \
				startpage \
				tint2 \
				vscode \
				xorg \
				zsh
			;;
		*)
			stow --no-folding "$@"
			;;
	esac
}

install "$@"

