#!/bin/bash

# For Arch Linux

# GitKraken has some issues when watching for files to change, so we need to raise the limit of
# watchers that are allowed on the system

if [[ $(uname -s) == "Linux" ]]; then
  INOTIFY_LIMIT=$(cat /proc/sys/fs/inotify/max_user_watches)
  NEW_LIMIT=524288
  if [[ $INOTIFY_LIMIT < $NEW_LIMIT ]]; then
    echo "inotify watcher limit will be increased from $INOTIFY_LIMIT" \
      "to $NEW_LIMIT"
    echo "fs.inotify.max_user_watches=$NEW_LIMIT" |
      sudo tee /etc/sysctl.d/40-max-user-watches.conf &&
        sudo sysctl --system
  fi
fi
