# Created for 5.2
alias pacman="pacaur"
alias em="emacs -nw"
alias ls="ls --color=auto"

alias npm-clean="rm -rf ./node_modules && npm install"
alias github="cd $HOME/Documents/GitHub"

alias SimpleHTTPServer="python2.7 -m SimpleHTTPServer 8000"

quiet() {
	$* > /dev/null 2>&1
}

export XDG_DESKTOP_DIR="$HOME/Desktop"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_TEMPLATES_DIR="$HOME/Templates"
export XDG_PUBLICSHARE_DIR="$HOME/Public"
export XDG_DOCUMENTS_DIR="$HOME/Documents"
export XDG_MUSIC_DIR="$HOME/Music"
export XDG_PICTURES_DIR="$HOME/Pictures"
export XDG_VIDEOS_DIR="$HOME/Videos"

XDG_CONFIG_HOME="$HOME/.config"
XDG_CACHE_HOME="$HOME/.cache"
XDG_DATA_HOME="$HOME/.local/share"
XDG_RUNTIME_DIR="/tmp"
XDG_DATA_DIRS="/usr/local/share:/usr/share"
XDG_CONFIG_DIRS="/etc/xdg"

PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"

source $HOME/.config/zsh/git-flow-completion.zsh
